README.markdown
Also split the website section in twain for devs and users.
=> Update readme to point to github

src/YeastTableModel.cpp
@Brewtarget/developers code review please
=> Fixes #18 - dead assignment in YeastTableModel::data

src/CMakeLists.txt, src/Testing.cpp, src/Testing.h
@Brewtarget/developers Need a review on this one
This adds a test case on basic recipe calculations so that we can easily tell if a commit breaks it.
=> Add all-grain recipe calculation unit test

src/database.cpp, src/recipe.cpp, src/recipe.h
This fix the bug #30.
The fix is very simple. I just duplicate the mechanism used for the other ingredients.
Please review
=> Fixes #30 - Recipe doesn't update automatically after yeast properties changes.

src/IbuMethods.cpp, src/IbuMethods.h, src/OptionDialog.cpp, src/RecipeFormatter.cpp, src/brewtarget.cpp, src/brewtarget.h, ui/optionsDialog.ui
First pull for implementation of IBU caluclations based on Greg Noonans work.  
Using 60 minutes boiltime as default for gravity correction (based on table from http://www.vthomebrewguru.com/a-bitter-subject-hops-aaus-ibus-hbus/ and https://www.homebrewersassociation.org/attachments/0000/2501/IBUs.pdf)
=> Noonan IBUs #7

src/ScaleRecipeTool.cpp
This fixes the bug #29 .
Please review
=> Fixes #29 - Bug in scale recipe calculation by efficiency

CMakeLists.txt, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_da.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts
Adds the following languages:
- Estonian
- Basque
- Galician
- Latvian
- Serbian
- Turkish
=> Import and update launchpad translations

CMakeLists.txt
Trying to build Brewtarget on Windows revealed a few issues. I will try to find and eliminate them. Here are these included in this pull request.
* Inverted logic on Multimedia DLL inclusion.
* MINGW_BIN having a redundant bin path.
=> [WIN] Correction of build issues.

src/brewnote.cpp, src/equipment.cpp, src/instruction.cpp, src/mash.cpp, src/mashstep.cpp, src/recipe.cpp, src/water.cpp
Issue is due to improper localization of database strings. Also fix as many
other improper localizations as I could find.
=> Fixes #77: bad input behavior for equipment specific heat

src/CMakeLists.txt, src/Testing.cpp, src/Testing.h
Make a test verifying post-boil losses do not affect the OG
=> Add post-boil loss OG test

src/brewtarget.cpp, ui/fermentableEditor.ui, ui/mainWindow.ui, ui/mashEditor.ui, ui/refractoDialog.ui
Some text mustn't be translatable. For example, date format field sould not be changed.
This will make translators'life easier and avoid some bugs.
=> Corrections of some translation parameters.

src/OptionDialog.cpp, src/PrimingDialog.cpp, ui/optionsDialog.ui, ui/primingDialog.ui
To me it much more logical and it was almost nothing to do.
=> Changes some checkboxes to radioButton when only one choice is possible.

src/FermentableDialog.cpp, src/FermentableDialog.h, src/FermentableSortFilterProxyModel.cpp, src/FermentableTableModel.cpp, src/HopDialog.cpp, src/HopDialog.h, src/HopSortFilterProxyModel.cpp, src/HopTableModel.cpp, src/MiscDialog.cpp, src/MiscDialog.h, src/MiscSortFilterProxyModel.cpp, src/MiscTableModel.cpp, src/YeastDialog.cpp, src/YeastDialog.h, src/YeastSortFilterProxyModel.cpp, src/YeastTableModel.cpp
New pull request based on the correct branch/revision.
=> Closes #6: real-time ingredient search

.travis.yml
Squashed to one commit and removed branch-whitelist
=> Add Travis CI file for OSX building

src/main.cpp
Was looking for a way to add a CLI arguments and I found that the code in
main.cpp was using a hand build function for this with a todo to use the correct
"QCommandLineParser" functionalities coming from QT5.
I replaced the old code with the new module and this provides 2 new cli options.
-h for help and -v for version.
This modification was made in order to pave the way for a cli configurable configDir.
=> Argument parsing now using QCommandLineParser.

src/AboutDialog.h, src/MainWindow.cpp, src/MainWindow.h, ui/mainWindow.ui
The donate buttons from the menu (2 button) and from the about box has been removed.
=> Remove donate buttons

.gitignore, .kateproject
Simple "project" file for Kate. Added features include source search, code analysis, source browsing, and code completion. Just open any file in the project with Kate, and the project opens.
=> Add a Kate project

src/DatabaseSchemaHelper.cpp
Closes #97: rebased to master branch.
=> Fixes bugs with brewday step numbering

src/BtTreeItem.cpp, src/BtTreeModel.cpp, src/BtTreeModel.h
- Modified model changing for item children insertion.
- Also added lots of const modifier to function in the model.
Note:
It's not as clean as it could but the other stuff is all good practice and lots of const that should already been here.
=> Fixes #98 : Crash when trying to create a new folder.

.gitignore, src/OptionDialog.cpp, src/OptionDialog.h, ui/optionsDialog.ui
While I was at it, changed the IBU Adjustment inputs from LineEdit to DoubleSpinBox. I couldn't determine how they're used though, so wasn't sure what the range should be. If someone knows, I'll modify the .ui file.
Side note: this is my first commit to this project and I just learned Qt, so I'm wide open to feedback!
=> Fixes #93: Convert units/formulas options to combo boxes

src/BtTreeItem.cpp, src/brewnote.cpp, src/brewtarget.cpp, src/brewtarget.h
Moved formated date method to brewtarget.cpp for reuse.
=> Made "First Brewed Date" in tree use user format.

src/Log.cpp, src/Log.h, src/brewtarget.cpp
- This fixes the problems of the static initialization before the system
options are read.
=> Moved initialization of stream to a separate function.

brewtarget.qrc, images/filesavedirty.svg, src/MainWindow.cpp, src/MainWindow.h, src/config.in, src/database.cpp, src/database.h
A lot of the comments I was getting from users was that they did not know
about how Brewtarget didn't save anythin until manually asked to. Since
the application wasn't warning them, I think its fairly normal to wonder
why you were asked about this when closing the app.
Now when the dirty status changes on the DB, the statusBar reads "Unsaved
Changes"
=> App now has a visual hint of unsaved changes.

src/BtTreeModel.cpp
Just forgot a case in my switch statement. That's been cleaned up, along with
a slight change to the error messages.
=> Closes #155: can't delete a style from the tree

src/EquipmentEditor.cpp, src/EquipmentEditor.h
Changes layout and enables automatic computation of Pre-boil volume.
=> Closes #153: improve equipment editor

src/RefractoDialog.cpp
=> Fixes #159: OG in Plato wrongly displayed in refracto dialog

ui/yeastEditor.ui
Is it OK like this ? I rebased my branch to be based on stable/2.3.1.
=> Fix #183 amountIsWeight behavior in YeastEditor

src/BtTreeView.cpp, src/MainWindow.cpp, src/MainWindow.h, src/RecipeFormatter.cpp, src/RecipeFormatter.h
For completely wrong reasons, I want to be able to export multiple recipes to a single HTML file, rather like we can with an XML file. So this does that.
=> Allows multiple recipes to be exported to HTML

vagrant/provision.yml
A debugger is a good thing to have.
=> Add gdb to packages installed on vagrant box

src/BtLineEdit.h
=> Closes #233 - Fix pedantic compiler warnings about extra ;

src/database.cpp
I simply make sure we can map from any string to a type. This impacts a few
places, but the code it pretty simple.
=> Closes issue #239 -- fault tolerant fromXML

src/BtLineEdit.cpp
For reasons I don't understand (other than I suck at testing code), I never
tested a BtLineEdit to see how the new input scaling works. In short, it
didn't. No matter what you entered, the default unit/scale was displayed. So
if you entered "20 qt" into a BtVolumeEdit, it would be interpreted as 20 L or
20 gallon, depending on what the field was set to.
The fix ends up being rather simple. BtLineEdit::toSI() invokes the proper logic 
to find the default unit/scale if it is called with force = false. I just had to figure out when
to invoke that logic in BtLineEdit::lineChanged().
After much screwing around, I figured out that we needed to invoke it only when
the user didn't include a unit/scale in the input. So if the user says "20 qt"
in a BtVolumeEdit, we won't go looking for the default …
=> Closes #238 -- Units on input are not working

src/CMakeLists.txt, src/HydrometerTool.cpp, src/HydrometerTool.h, src/MainWindow.cpp, src/MainWindow.h, ui/mainWindow.ui
Add a Hydrometer adjustment tool on the tool menu.  Adapted from the ConverterTool.
=> Bug #1109730 - Hydrometer Tool

src/BrewDayScrollWidget.cpp, src/BrewDayWidget.cpp, src/RecipeFormatter.cpp
Develop is now printing something out for recipe and brewday.
=> Fix for #263 - Printing not working in develop

src/MashDesigner.cpp
Patch is from @mattipt
- http://enneu.net/files/mashdesigner.patch
=> Fixes #279: mash designer slider value inconsistent

scripts/add-to-default-db.py, scripts/example-ingredients.json
It sucks directly editing default_db.sqlite. Just make a big .json file and let the script import the data into the database.
=> Script to make it easy to update the default db with new ingredients

src/EquipmentEditor.cpp
Maybe this works better? It's a tricky message to word well, and I won't claim
this does it. But it collapses all three into one, and I think gives a bit
better hint?
=> Closes(?) #298 -- Tun Volume Entered is 0

src/database.cpp
Apparently, resetting the index on an empty table isn't a good idea. Someday (very soon), I am fixing the waters.
Oh. And apparently a lot of whitespace fixes. Hates
=> Closes #303 -- Copy database fails

CHANGES.markdown, brewtarget.qrc, css/inventory.css, src/BrewDayScrollWidget.cpp, src/BrewDayScrollWidget.h, src/CMakeLists.txt, src/Html.cpp, src/Html.h, src/InventoryFormatter.cpp, src/InventoryFormatter.h, src/MainWindow.cpp, src/MainWindow.h, src/RecipeFormatter.cpp, src/RecipeFormatter.h, src/database.cpp, src/database.h, ui/mainWindow.ui
Adds the ability to print and export the available inventory.
Also refactors the recipe and brewday printing code. This made adding this
feature easier.
=> Adds an inventory list

src/BeerXMLElement.cpp, src/brewnote.cpp, src/equipment.cpp, src/fermentable.cpp, src/hop.cpp, src/mash.cpp, src/mashstep.cpp, src/misc.cpp, src/recipe.cpp, src/recipe.h, src/style.cpp, src/water.cpp, src/yeast.cpp
It's just good coding style...
Single source of truth prevents people from typo'ing
=> Const QString all the Strings in all the BeerXMLElements

src/HydrometerTool.cpp, src/HydrometerTool.h
My hydrometer is calibrated to 68F.  The hydrometer tool was set to 60F as the calibrated temperature. I added a field to allow the user to edit the calibrated temp.
=> Added temp calibration option to HydrometerTool.cpp

translations/bt_pt_BR.ts
=> Fix pt-BR translation

README.markdown
Corrected the entry in the dependencies list.
=> corrected libqt5sql-psql to libqt5sql5-psql

translations/bt_nl.ts
Lots of updates to the Dutch translation.
I wanted to point out, that translations/README pointed me to download some files from Launchpad, but I couldn't access the files. (The contents of the README seem to be very outdated, because the link is pointing to a repository on Launchpad that probably has been moved to GitHub a while back.)
Let me know where I can help if I have made things complicated.
I used QT Linguist for updating the .ts files BTW
Reviewed (most of) the translations in my locally build brewtarget.
=> Dutch translation

translations/bt_ru.ts
A bit of Russian translation strings.
=> Russian translation

src/BtLineEdit.cpp
Imported the patch from develop.
It looked ok on my computer.
@pricelessbrewing review and merge?
=> Closes #158. Imported the patch from develop

src/database.cpp
Removed throws and replaced with error handling in database.cpp to prevent crashes when importing bad XML.  This stops the files in #280 and #420 from crashing, but other bad xml can still cause a crash elsewhere.
=> Removed throws and replaced with error handling.

src/database.cpp
Fixes #436 by reordering execution of delete statements and deleting the copy's record from inventory.
=> Delete fermentable fix

src/BtFolder.cpp, src/BtTreeModel.cpp, src/CMakeLists.txt, src/MainWindow.cpp, src/database.cpp
Compile time warnings really annoy me. Qt 5.15 introduced a bunch of them. I am cleaning them here in a single commit instead of sneaking them in somewhere else.
=> Cleaning up a bunch of deprecation warnings

scripts/add-to-default-db.py, scripts/example-ingredients.json
Refactored the Python script add-to-default-db.py and added a Context manager for database queries.
this way the DB is never left in an error state when running the script.
Also cleaned up the code to do more with less code.
=> Context handler with error handling to Python script: add-to-default-db.py

src/Log.cpp, src/Log.h, src/OptionDialog.cpp, src/OptionDialog.h, src/brewtarget.cpp, src/brewtarget.h, ui/optionsDialog.ui
I've done some coding towards adding functionality to the GUI to let the user decide logging level and where to put the log files.
I mentioned this in #474 asking if it was of interest.
So I created this PR, having no expectation that it will be merged.
I also had a thought that we could implement a command-line arguments, i.e. brewtarget --logging, to activate the logging options for debugging maybe?
All feedback is most welcome!
closes #474
=> closes #474 Adding logging option

translations/bt_sv.ts, translations/lpad/bt-sv.po
Completed the translation into swedish.
=> Finished translating into swedish

src/brewtarget.cpp
One-line fix for https://github.com/Brewtarget/brewtarget/issues/495
=> Fix for issue #495 - log version number and platform info

src/main.cpp
Fix for https://github.com/Brewtarget/brewtarget/issues/526.  Based on one of the simpler 'standard' approaches published on StackOverflow.
=> Prevent multiple simultaneous instances of Brewtarget

src/CMakeLists.txt, src/RadarChart.cpp, src/RadarChart.h, src/WaterEditor.cpp, src/WaterEditor.h, src/database.h, src/recipe.cpp, src/recipe.h, src/water.cpp, src/water.h, ui/waterEditor.ui
I was starting to look at water profile tools and I thought a nice first step might be a visualisation, so I created a simple radar chart.
=> Add radar chart to Edit Water dialog

src/main.cpp
This is a fix for https://github.com/Brewtarget/brewtarget/issues/533, per the solution in the link at https://stackoverflow.com/questions/42549904/qsharedmemory-is-not-getting-deleted-on-application-crash as suggested by @xzfantom.
=> Fix for false-positives about two instances running after a crash

.github/workflows/linux-ubuntu.yml
Xerces got us beyond one problem, now for xalan
=> And now with xalan

.github/workflows/mac.yml
#545 Building mac package in native environment
=> Mac package

.github/workflows/linux-ubuntu.yml, .github/workflows/mac.yml, .github/workflows/windows.yml, CMakeLists.txt, src/CMakeLists.txt, src/Testing.h
As mentioned in #456 one of the working ways to build app for windows is using MSYS2. To avoid finding required libs for different build systems for Windows I added some code to CMakeLists.txt to find it automatically.
=> CI win + xalan

ui/waterEditor.ui
The water editor was always kind of unpleasant to look at, but I couldn't figure a better way. With the addition of the radar map, I could no longer ignore it and I had a better way.
It still isn't perfect, but this somewhat more digestable.
=> Rebalances the water editor

CMakeLists.txt, src/beerxml.cpp, src/recipe.h
I found a typo in the XML mappings (my bad copy-and-paste), so have fixed and also made sure we're using PropertyNames constants throughout.  Changed CMake min version to 3.16 so I could compile on my system (see discussion at https://github.com/Brewtarget/brewtarget/discussions/559).
=> Minor fixes / tidy-up to XML mappings

COPYRIGHT, brewtarget.qrc, images/grain2glass.svg, ui/mainWindow.ui
I had never actually intended to leave the tool bar with the words "Brew It". I had wanted to put an icon in its place, but what sort of icon would be meaningful? And, just as important, free enough for us to use?
So I made this. I won't say "drew", because I really mostly copy/pasted other resources we already had. I did, however, add my own numeric 2.
=> new icon for brewit

.github/workflows/linux-ubuntu.yml, .github/workflows/mac.yml, .github/workflows/windows.yml
Added the Boost libraries to the actions, lets hope it works!
=> adding boost library to actions.

README.markdown, src/CMakeLists.txt, src/TableSchemaConst.h
Closing #604 
With some help from @matty0ung can submit this PR which fixes the error causing the tests to failing.
And when I say *"With some help from"* I mean: HE supplied the solution, I just edited a file and pushed a commit. 😆
=> fixing table column name error causing Testing crash, and Mac build error.

src/database.cpp
Fix for https://github.com/Brewtarget/brewtarget/issues/606
=> Wrong version of getParentRecipe called for MashStep and BrewNote from recipe versioning function

src/BtTreeView.cpp, src/BtTreeView.h
fixes #609 
1. I added a null-check for recipe so that when you right click the top-level-item in the recipe tree 'Recipes' you get the folder menu but with no DELETE function.
2. Also added the above mentioned folder-specialized context menu.
3. fixed a few, not all private varables prefixed with _ to be prefixed with m_ instead.
=> Fixes Bug in issue #609,

src/xml/BeerXml.cpp
This is a fix for https://github.com/Brewtarget/brewtarget/issues/626
=> Fix for writing flySparge & batchSparge values to BeerXML

src/BtFieldType.cpp, src/BtLineEdit.cpp, src/BtLineEdit.h, src/MainWindow.cpp, src/model/NamedEntity.h, ui/mainWindow.ui
This fixes the issue of recipe efficiency not being modifiable.  (It's a bug from the changes I made in https://github.com/Brewtarget/brewtarget/pull/631 where a signal didn't get emitted.)
It should be possible to merge this either before or after https://github.com/Brewtarget/brewtarget/pull/640 and https://github.com/Brewtarget/brewtarget/pull/638.
=> Fix for https://github.com/Brewtarget/brewtarget/issues/641

.github/workflows/linux-ubuntu.yml
Per discussion at https://github.com/Brewtarget/brewtarget/issues/665
=> Add Ubuntu 22.04 build to GitHub actions

src/Application.cpp, src/Application.h, src/CMakeLists.txt, src/InventoryFormatter.cpp, src/Localization.cpp, src/MainWindow.cpp, src/MainWindow.h, src/MashDesigner.cpp, src/TimerWidget.cpp, src/database/Database.cpp, src/database/DatabaseSchemaHelper.cpp, src/main.cpp, src/model/Recipe.cpp, src/unitTests/Testing.cpp, src/unitTests/Testing.h
This is, hopefully, a step towards getting to the bottom of https://github.com/Brewtarget/brewtarget/issues/669
=> Improve logic for determining resource directory, plus fix checking for new version

translations/bt_tr.ts
Before release of 3.0.4 I tried my best :) This is second translation update to Turkish language. Translated more than 95%.
=> Second update to bt_tr.ts

CHANGES.markdown
=> Fixed release notes

CHANGES.markdown, CMakeLists.txt
This is a first attempt to get the Mac build to do static linking -- seeing as how we have had such problems with getting all the right dynamic libraries in all the right places when creating bundles with CPack.
=> More tweaks to Mac build

src/BtTreeModel.cpp, src/model/Salt.cpp, src/tableModels/BtTableModel.h, src/tableModels/SaltTableModel.cpp, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts, ui/mainWindow.ui
I had to fix the initializer for the Salt object. The amount_is_weight, the amount and the addTo fields were all kind of cross wired.
The harder problem was the removeDuplicates method. I was unsure of the side effects of removing the deleted and not displayed tests, so I created a new method called `removeDuplicatesIgnoreDisplay` and used that in the SaltTableModel.
Things seem to be working better now.
=> Water chemistry misbehaving -- closes #705

src/measurement/PhysicalQuantity.cpp, src/measurement/SystemOfMeasurement.cpp, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts
This is the missing enum mappings
=> Fix for https://github.com/Brewtarget/brewtarget/issues/708

src/OptionDialog.cpp, src/PersistentSettings.cpp, src/database/Database.cpp, src/database/Database.h, src/model/Hop.cpp, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts
Fixes for https://github.com/Brewtarget/brewtarget/issues/695 and https://github.com/Brewtarget/brewtarget/issues/694
=> Fixes for enum mapping and persistent settings file name

CHANGES.markdown, CMakeLists.txt, src/HopEditor.cpp, src/database/Database.cpp, src/model/Hop.h, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts, ui/hopEditor.ui
Fix for https://github.com/Brewtarget/brewtarget/issues/717
=> Remove duplicate combo box entries on Hop editor

CHANGES.markdown, src/model/Recipe.h, ui/recipeExtrasWidget.ui
Tidy-up and small bug-fixes for 4.0 release
=> Tidy-up for 4.0 release

src/model/Recipe.cpp
For https://github.com/Brewtarget/brewtarget/issues/801
=> Fix wrongly-emitted error message

CHANGES.markdown, CMakeLists.txt, meson.build, src/database/DatabaseSchemaHelper.cpp
Fix for the data conversion failure part of https://github.com/Brewtarget/brewtarget/issues/804.  Also fix orphan inventory item for same ticket.
=> Drop indexes we no longer need and that give upgrade errors

.github/workflows/linux-ubuntu.yml, .github/workflows/mac.yml, .github/workflows/windows.yml, CHANGES.markdown, CMakeLists.txt
See https://github.com/Brewtarget/brewtarget/issues/806
=> Fix for DefaultContent004-MoreYeasts.json not in cmake files

.github/workflows/windows.yml, .signpath/artifact-configurations/default.xml, CHANGES.markdown, src/RecipeFormatter.cpp, src/database/DatabaseSchemaHelper.cpp, src/editors/FermentableEditor.cpp, src/editors/HopEditor.cpp, src/editors/MiscEditor.cpp, src/editors/YeastEditor.cpp, src/model/BrewNote.cpp, src/model/IngredientBase.h, src/model/Recipe.cpp, src/model/Yeast.cpp, src/model/Yeast.h, src/sortFilterProxyModels/RecipeAdditionYeastSortFilterProxyModel.cpp, src/tableModels/RecipeAdditionYeastTableModel.cpp, src/tableModels/RecipeAdditionYeastTableModel.h, src/widgets/BtComboBox.cpp, src/widgets/BtComboBox.h, src/widgets/SmartField.cpp, src/widgets/SmartField.h, ui/yeastEditor.ui
Fixes for https://github.com/Brewtarget/brewtarget/issues/812 and https://github.com/Brewtarget/brewtarget/issues/814
=> Fixes for inventory problems and missing yeast attenuation on DB upgrade, plus first stab at signing Windows binaries

.github/workflows/mac.yml, src/MainWindow.cpp, src/model/Boil.h, src/tableModels/MashStepTableModel.cpp, src/tableModels/TableModelBase.h, src/widgets/SmartField.cpp, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts
See https://github.com/Brewtarget/brewtarget/issues/817.
Fixes for a couple of asserts - one where we had optionality wrong, another where we were incorrectly treating a type as being of variable physical quantity when it is not
=> Fixes for a couple of asserts

CMakeLists.txt, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts
The change to `CMakeLists.txt` should be another option for fixing https://github.com/Brewtarget/brewtarget/issues/843 (in case anyone else hits it).
=> Fixes for build with slightly older CMake

.github/workflows/linux-ubuntu.yml, CHANGES.markdown, src/MainWindow.cpp, src/MainWindow.h, src/database/ObjectStore.cpp, src/editors/BoilStepEditor.cpp, src/editors/BoilStepEditor.h, src/editors/EditorBase.h, src/editors/FermentationStepEditor.cpp, src/editors/FermentationStepEditor.h, src/editors/MashStepEditor.cpp, src/editors/MashStepEditor.h, src/model/BoilStep.cpp, src/model/BoilStep.h, src/model/FermentationStep.cpp, src/model/FermentationStep.h, src/model/MashStep.cpp, src/model/MashStep.h, src/model/NamedEntity.h, src/model/Step.cpp, src/model/Step.h, src/model/StepBase.h, src/tableModels/BtTableModel.h
This fixes https://github.com/Brewtarget/brewtarget/issues/847 and https://github.com/Brewtarget/brewtarget/issues/831
=> Fixes for adding mash/boil/fermentation steps

CHANGES.markdown, src/database/DatabaseSchemaHelper.cpp
Fix for remaining problem in https://github.com/Brewtarget/brewtarget/issues/840
=> Fix upgrade to take account of salt additions with "When to add" of "Never"

scripts/buildTool.py
Grumble grumble Python run-time errors. :smile_cat:
=> Build script fix

CHANGES.markdown, src/model/NamedEntity.cpp, src/model/OwnedByRecipe.h, src/model/OwnedSet.h, src/model/Recipe.cpp, src/model/Recipe.h, src/model/StepOwnerBase.h, src/model/SteppedBase.h, src/model/SteppedOwnerBase.h
Should fix some, if not all, of the problems in https://github.com/Brewtarget/brewtarget/issues/868 and https://github.com/Brewtarget/brewtarget/issues/866.
=> Better way of doing owned sets in Recipe, which also fixes Recipe copy problems

CMakeLists.txt, translations/bt_da.ts
This is an uptodate translation file for danish and I have added a line i CMakeLists.txt to include it when building executables.
There are a few words/phrases in the userinterface still in english. I assume these are not integrated in in the qt UI.
Also there is some accelerators not working. This also goes for english UI.
=> Danish translation

CMakeLists.txt, meson.build
Hopefully the final bit before the 4.0.10 release!
=> Update version numbers

CHANGES.markdown, CMakeLists.txt, meson.build, src/Application.cpp, src/Application.h, src/MainWindow.cpp, src/MainWindow.h, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts
Fixes https://github.com/Brewtarget/brewtarget/issues/878
=> Fix for crashes in UI prompting download of latest version

CHANGES.markdown, src/PrintAndPreviewDialog.cpp, src/PrintAndPreviewDialog.h
Fixes https://github.com/Brewtarget/brewtarget/issues/873
=> Fix stack overflow in print preview dialog on Windows

translations/bt_da.ts
With translation of some until now untranslated phrases and a few corrections.
=> Updated danish translation

CHANGES.markdown, CMakeLists.txt, meson.build, src/editors/EquipmentEditor.h, src/editors/StyleEditor.h, src/widgets/BtComboBoxNamedEntity.cpp, src/widgets/BtComboBoxNamedEntity.h, translations/bt_da.ts, ui/equipmentEditor.ui, ui/styleEditor.ui
This should fix https://github.com/Brewtarget/brewtarget/issues/913.
=> Fix combo box crash when selected value is "child" record

CHANGES.markdown, src/measurement/Unit.cpp
See https://github.com/Brewtarget/brewtarget/issues/923
=> Fix for quarts being treated as pints

src/Algorithms.cpp, src/model/Recipe.cpp, src/model/Recipe.h, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_da.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts
See https://github.com/Brewtarget/brewtarget/issues/929
=> Fix for crash when creating new recipe

translations/bt_da.ts
And a few other improvements. This has no hurry. Can just be added when new version has to be made for other reasons.
=> New danish translation file with correction for causing wrong date on recipeExtrasWidget

CHANGES.markdown, src/RecipeExtrasWidget.cpp, src/widgets/BtComboBoxBool.cpp, ui/waterEditor.ui
This fixes https://github.com/Brewtarget/brewtarget/issues/943 and https://github.com/Brewtarget/brewtarget/issues/944
=> Fixes for crashes when trying to change carbonation volumes and when saving in water editor

CHANGES.markdown, src/Application.cpp, src/database/ObjectStoreTyped.h, src/database/ObjectStoreWrapper.h, src/model/Recipe.cpp, src/trees/TreeModel.cpp, src/trees/TreeModelBase.h, src/trees/TreeNode.cpp, src/trees/TreeNode.h, src/trees/TreeNodeBase.h, src/widgets/BtComboBoxEnum.cpp
Fixes for https://github.com/Brewtarget/brewtarget/issues/949 and https://github.com/Brewtarget/brewtarget/issues/936
=> Fix copying recipes etc

CHANGES.markdown, CMakeLists.txt, meson.build, src/database/ObjectStoreTyped.cpp, src/editors/EditorBaseField.h, src/editors/EquipmentEditor.cpp
Fixes https://github.com/Brewtarget/brewtarget/issues/957
Also bumped version numbers
=> Fix missing editor logic for checkboxes

CHANGES.markdown, src/database/Database.cpp
Fix for https://github.com/Brewtarget/brewtarget/issues/958
=> Fix DB backup error message during upgrade for PostgreSQL

CHANGES.markdown, meson.build, src/CMakeLists.txt, src/MainWindow.cpp, src/database/Database.cpp, src/database/DatabaseSchemaHelper.cpp, src/database/ObjectStoreWrapper.h, src/editors/EditorBaseField.h, src/editors/MashStepEditor.cpp, src/model/NamedEntity.cpp, src/model/NamedEntity.h, src/model/Recipe.cpp, src/model/Recipe.h, src/trees/RecipeTreeModel.cpp, src/trees/RecipeTreeModel.h, src/trees/TreeModel.cpp, src/trees/TreeModel.h, src/trees/TreeModelBase.h, src/trees/TreeModelChangeGuard.cpp, src/trees/TreeModelChangeGuard.h, src/trees/TreeNode.cpp, src/trees/TreeNode.h, src/trees/TreeNodeBase.h, src/trees/TreeViewBase.h, src/widgets/BtComboBoxNamedEntity.h, ui/mashEditor.ui, ui/mashStepEditor.ui
For:
- https://github.com/Brewtarget/brewtarget/issues/961
- https://github.com/Brewtarget/brewtarget/issues/964
- https://github.com/Brewtarget/brewtarget/issues/965
- https://github.com/Brewtarget/brewtarget/issues/967
=> Various fixes

CHANGES.markdown, CMakeLists.txt, meson.build, src/measurement/Unit.cpp, src/trees/TreeModelBase.h, src/trees/TreeNodeBase.h, src/trees/TreeViewBase.h, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_da.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts
Fix for https://github.com/Brewtarget/brewtarget/issues/974
=> Fix for crash when deleting item from tree

CHANGES.markdown, src/Application.cpp, src/Application.h, src/database/Database.cpp, src/editors/EditorBase.h, src/model/Recipe.h, src/trees/TreeModelBase.h, src/trees/TreeNode.h, src/trees/TreeNodeBase.h, src/trees/TreeView.cpp, src/trees/TreeViewBase.h, src/widgets/BtComboBoxNamedEntity.cpp
Hopefully fixes https://github.com/Brewtarget/brewtarget/issues/984
=> Fix tree problems, add check for too-new DB schema, etc

CHANGES.markdown, src/trees/TreeModelBase.h, src/trees/TreeModelChangeGuard.h, ui/mainWindow.ui
Fix for https://github.com/Brewtarget/brewtarget/issues/990
=> Fix for problems with creating and deleting BrewNotes

CHANGES.markdown, src/qtModels/tableModels/TableModelBase.h
Fixes Fixes https://github.com/Brewtarget/brewtarget/issues/1003
=> Fix sorting

CHANGES.markdown, src/editors/EditorBase.h, src/model/OwnedSet.h, src/undoRedo/Undoable.cpp
Fixes https://github.com/Brewtarget/brewtarget/issues/1008
=> Fix inadvertent moving of steps from editor

CHANGES.markdown, src/OptionDialog.cpp
Fixes https://github.com/Brewtarget/brewtarget/issues/1010
=> Add Lovibond as general color unit option on Options Dialog

CHANGES.markdown, src/serialization/ImportExport.cpp
Fix for https://github.com/Brewtarget/brewtarget/issues/1025
=> Fix default file extension handling for XML export
