src/MainWindow.cpp
The problem appears only if you configure EBC as default color unit in configuration because after changing the style, the color range was updated directly in SRM without taking care of the default unit.
=> fixes #2 - Color range wrongly updated after style change

src/recipe.cpp
I found this little issue while reading the code. I haven't seen any impact, but it may solve a bug.
=> Fix late addition sugar key in Recipe::recalcBoilGrav

README.markdown
Trying to get setup on a new debian/jessie machine, needed to install
qttools5-dev-tools in order to build.
=> Add missing qt5 package to readme

src/MainWindow.cpp
Fixing issue https://github.com/Brewtarget/brewtarget/issues/39 : Not unnecessarily converting the QString filename before feeding it to a QFile.
=> issue:#39 - Can not export recipe.

src/BtLineEdit.cpp, src/SIWeightUnitSystem.cpp
I put everything back to using kg as the default unit for SI weight, as that
was how it is stored in the db. Not sure if it is closed, since I need to do
some more testing.
=> Issue #28 -- BtMassEdit fields are wrong

src/EquipmentEditor.cpp
This was caused by the editProperty field not being set on the
tunSpecificHeat_calGC field. Because we didn't know which property to get, the
code just displayed ?
=> Bug #47 -- specific heat displays ?

src/BeerXMLElement.cpp
change the floating point format to better match beerXML v1.0
From the specification:
"- Floating Point - A floating point number, usually expressed in its simplest form with a decimal point as in "1.2", "0.004", etc...  Programs shall endeavor to store as many significant digits as possible to avoid truncating or losing small values.'
This should have no impact, but it should ensure that the exported beerXML files will be readable by every software that respects the standard.
=> Change floating point format in beerXML to fit with the standard

src/OgAdjuster.cpp, src/PitchDialog.cpp, src/PrimingDialog.cpp, src/RefractoDialog.cpp, ui/ogAdjuster.ui
BtLineEdit includes all the display unit management inside, all value to display must be passed to setText() in the default sytem unit. It is BtLineEdit who takes care of displaying the value in the right unit. Doing this way is ok, but we may find a better way of handling. You could create a class BtValue which would contains its value is default unit, and have all necessary methods to return the value in another unit. This is an idea, but I don't know if it is a good one.
It's really frustrating that every fixes regarding BtLineEdit seams to break something else every time.
=> Fixes wrong field display.

src/database.cpp, src/recipe.cpp
I've previously added the function to update recipe after yeast change, but it took only the yeast already in the recipe at loading. I've forgotten to add the signal connection after yeast addition. I've also added the ABV recalc for recipe update after any yeast change. I hope not forgetting anything this time.
=> Add dynamic signal connection for yeast addition + ABV update

CMakeLists.txt, src/CMakeLists.txt, src/TimerWidget.cpp, src/TimerWidget.h
This allow to compile and execute Brewtarget without QtMultimedia.
It may allows developers to develop and test on the platforms that have a conflict on the Gstreamer version linked with QtMultimedia and QtWebKit.
The only drawback is that the timer can't play any sound.
This is a temporary fix for the bug #9
=> Add compilation flag to disable QtMultimedia.

src/Testing.cpp, src/recipe.cpp
Whole cone hops are now considered to have a utilization adjustment
of 1.0. Plugs have an adjustment of 1.02, and pellets have an
adjustment of 1.10.
=> Fixes #64: leaf/plug utilization adjustment is backwards

ui/primingDialog.ui, ui/refractoDialog.ui
- In primingDialog
- In refractoDialog
Previously, the width was too small for some text DPIs, cutting off
digits and text.
=> Fixes #69: allow BtLineEdits to expand to 128px

src/fermentable.cpp, src/hop.cpp, src/misc.cpp, src/style.cpp, src/yeast.cpp
The problem was that simple double properties of the ingredients
were being passed through the localization procedures in the
Brewtarget class when they should not have been.
=> Fixes #65: bad ingredient amount behavior in non-US locales

src/brewtarget.h
- In brewtarget.h, there were many case of the use of Unit::Unit:: which might have
been caused by a faulty find and replace.
- G++ and Clang seemed ok with accepting this but not MSVS.
=> Removed redundant namespace.

src/BrewDayScrollWidget.cpp
This fixes #86 and change some odd behaviors.
Now when you add a new instruction without giving a step number, it is added to the end of the list (feels much more natural). I've also cleared the two field Name and Step after the instruction is added.
I've fixed another bug found while trying to fix the first one. The pushDown button makes all crash when trying to move down the last instruction.
Please review and give me your feedback.
=> Fixes #86: bugs in BrewDayScrollWidget

src/ScaleRecipeTool.cpp
But only if the scaling is by volume, since the volumes will still match if
the scaling is by efficiency.
=> Fixes #91: scale recipe tool should remove equipment

src/BrewDayScrollWidget.cpp, src/BrewDayWidget.cpp, src/BtLineEdit.cpp, src/MainWindow.cpp, src/RecipeFormatter.cpp, src/RecipeFormatter.h, src/UnitSystem.cpp, src/UnitSystem.h, src/brewtarget.cpp, src/brewtarget.h, src/recipe.cpp, src/recipe.h, ui/mainWindow.ui
I changed almost all the behavior of the getTextFormat function in order to make it smaller and easier to maintain. I split this function in order to reuse all sub-function for BBCode extraction.
I change many thing to use the same unit and scales as in the main interface (it seems more logical).
Doing this I found a bug on the displayAmount function which was trashing the precision parameter in some cases.
I think that it can still be improved, but it is quite OK now.
I didn't give an implementation for the BBCode function as it would be considered as a new feature (even if I'd really like to see it included into 2.2.0), but it will be very easy to write know, as it will be base on the text format extract.
One other thing I did, is to clean the calories management. Before that it was …
=> Improve recipe export (text) & add BBCode export

src/recipe.cpp
Implementation of a new calculation method for ABV. It reduce de error on ABV calculation for strong beers. Under 5% of alcohol the result is quite similar to the former formula.
This closes the enhancement request #48.
=> Closes #48: more accurate ABV calculation

src/Testing.cpp, src/Testing.h
It is imperative that anything we do in test does not affect
any instance of Brewtarget.
- I changed the organization name to remove the overlap.
- I also cleared the settings used inside the test suite at cleanup.
=> Made sure Test Settings are not interfering with Production.

src/FermentableTableModel.cpp, src/HopTableModel.cpp, src/MashStepTableModel.cpp, src/MiscTableModel.cpp, src/YeastTableModel.cpp, src/fermentable.cpp, src/fermentable.h
This is a first approach in order to change the weird checkbox used for Mashed option.
This commit aims to improve display avoiding manual resizing.
I need to find a way to hide one of the two parameters "Steeped" or "Not Mashed" regarding the fermentable type.
This branch fixes the bug #81
=> Fixes #81: Improvement/weird check box

configure
* it stops whatever went bad
* (so, do not show "cd build and make" if sth went wild...)
* creates directory 'build' if not exists
=> Fixing ./configure script

src/MiscTableModel.cpp, src/misc.cpp, src/misc.h
This commit changes the checkbox used for amount type in Misc tab the same way I've changed those of fermentable tab. I missed this one when I did it.
=> Change weird checkbox for misc amount type

src/CMakeLists.txt, src/Log.cpp, src/Log.h, src/MainWindow.cpp, src/MainWindow.h, src/brewtarget.cpp, src/brewtarget.h
I had two problems with the current state of Brewtarget. First, the log
file was pretty useless when trying to debug error because  it's used
in too few places and does not store major events as to used when
looking at the user flow.
The second was that I am in thre process of trying to remove all OS
specific processing from Brewtarget.h and Brewtarget.cpp. I think this
class shouldn't care on which platform it runs and should also be way
clearer as it is one of the central classes.
Here is what was done.
- Extracted all logging functionalities whilst keeping the same wrapper
in Brewtarget.
- Created a Log class to handle all logging.
- Log is now using RAII on all stream and file descriptors.
- Log is also now thread-safe.
- Added INFO and DEBUG case for future inclusion in the …
=> Refactored and extracted logging facilities.

src/Log.cpp, src/Log.h, src/MainWindow.cpp, src/OptionDialog.cpp, src/TimerWidget.cpp, src/brewtarget.cpp, src/brewtarget.h, src/database.cpp, src/main.cpp
This commit introduces the possibility of running brewtarget on a custom
database folder which will not impact your normal usage of the
Application.
This is intended for people with multiple version of Brewtarget and for
people helping test and debug the application.
* Modification to the settings made while debugging the application no
longuer interfere with normal settings.
* Introduction of the --user-dir cli option which allows the caller to
point to a directory containg the DB. This option will not store
itself in the settings. Meaning running brewtarget again without param
will revert to the known user data directory.
* There were a lot of "file and directory arithmetics" implicated in
this modification. Things like adding slash, double slash, backward
slash, ... at the end of …
=> Introduction of the user-dir cli option.

css/brewday.css, src/BrewDayScrollWidget.cpp
The Brew day pdf/html output don't keep the original line breaks.
I've added a style in the css (white-space: pre-wrap) that keep them.
=> Break lines in the notes of the brew day html output

src/pstdint.h
I've modified pstdint.h to check for VS2012 and up which have their own version of stdint.h, similarly to what's already being done for GCC. Without this change VS2015 report redefinition errors and the build fails.
=> Check for Visual Studio in pstdint.h

src/Testing.cpp
Adjust the batchSize and boilSize by - trubChillerLoss_l to compensate for
trubChiller loss.
=> Closes #161: brewtarget_tests fail

src/brewtarget.cpp
Fixed the warning 'QCoreApplication::applicationDirPath: Please instantiate the QApplication object first' which appears on Windows builds. It also makes sure an empty QApplication pointer isn't used.
=> Fixed bad static initialization of config directory

src/BtLineEdit.cpp, src/BtLineEdit.h, ui/recipeExtrasWidget.ui
It makes no sense to have these in any other scale by default. Users
can just enter the number of days without specifying units to set
ageing in days.
=> Fixes #184 All ageing times in Extras tab are scaled to days.

src/BtLineEdit.cpp, src/FermentableTableModel.cpp, src/HopTableModel.cpp, src/MashStepTableModel.cpp, src/MiscTableModel.cpp, src/UnitSystem.cpp, src/UnitSystem.h, src/WaterTableModel.cpp, src/WaterTableModel.h, src/YeastTableModel.cpp, src/brewtarget.cpp, src/brewtarget.h
Assuming I did not utterly and completely make a mess of it, this should allow
us to scale input. What I mean by that is if you specify the scale of a field
to be (for example) grams, and then type 19 into that field, brewtarget will
now interpret this as 19 grams, not 19 kg.
The unit&scale mechanisms were about 90% in place. I had to modify a few
method signatures, a few method invocations in the tables and ONE LINE in
BtLineEdit. Everything should play by the rules now. 
I should also mention I had to add the necessary code to the WaterTableModel to deal with units and scales. One day, I really want to take the time to make that stuff work.
=> Scale on input -- item #179

src/BtTreeView.cpp, src/BtTreeView.h, src/EquipmentEditor.cpp, src/EquipmentEditor.h, src/FermentableDialog.cpp, src/FermentableDialog.h, src/HopDialog.cpp, src/HopDialog.h, src/MiscDialog.cpp, src/MiscDialog.h, src/StyleEditor.cpp, src/StyleEditor.h, src/YeastDialog.cpp, src/YeastDialog.h
It wasn't so much a bug as an intentional design choice. The problem I avoided
solving was that the tree didn't know which editor to call.
I fixed that by modifying the signal to call a BtTreeView slot, which figured
out the folder and called the proper editor. It required me adding a new
method to all of the editors, and modifying the signal slightly.
=> Closes #117: New ingredient can't be created into a folder

src/BtTreeModel.cpp
The rebase generated way too many collisions. It was faster to create a new
branch.
Moving folders used childCount() as the test condition in a for loop. Because
I moved the children into the new folder, childCount() got decremented by one.
This resulted in the loop counter getting incremented, the test condition
getting decremented and me moving only about half the children.
The fix is a bit more involved, since I don't move folders. I capture the
starting childCount at the start and use that for the test condition, and I
only take the first non-folder child through the whole operation. The only
tricky part is that I don't move folders, so I have to increment a counter to
indicate where the first non-folder item is.
=> Closes #195 again .. again?

CMakeLists.txt, src/CMakeLists.txt
Change is necessary to enable distinct data and binary packages.
Specifically, this is to avoid the lintian warning
[arch-dep-package-has-big-usr-share](https://lintian.debian.org/tags/arch-dep-package-has-big-usr-share.html)
=> Split install into data and runtime components

src/OptionDialog.h, src/database.cpp, src/fermentable.h, src/hop.h, src/instruction.h, src/misc.h, src/recipe.h, src/water.h, src/yeast.h
populateChildrenTables() requires the tableName hash to be populated, but
the hash can't be populated until after DatabaseSchemaHelper::migrate is
called. With the way the methods are written now, this leads to a chicken-egg
sort of problem.
I solved the problem by simply have populateChildrenTables() prepopulate the
hash. On the one time we need to call that method, the hash will get
initialized twice. I could maybe fix that, but it seemed an awful lot of work
for something that should happen once. In a broader question, shouldn't the
populateChildrenTables be part of the migrate code?
The changes to the header files are simply cleaning some compiler warnings.
=> Closes #206 - core while populating child tables

src/database.cpp, src/database.h
The easy part is the problem defintion. In one of my multiple refactorings,
the removeIngredientFromRecipe method attempted to remove a line from
instruction_children, and that table doesn't exist.
I thrashed around a little, but it is one exception for just one class and I
didn't feel a more generic solution was required. This is, admittedly, a
little hackish and I will likely come to regret it later.
The change to database.h is removing a qDebug() line that I swear I have
removed at least three times already.
=> Closes #211 - Crash recreating brewday instructions.

ui/mashWizard.ui
That was odd. Apparently, deleting widgets in designer can sometimes leave
behind zorder tags. According to those same sources, the only way to fix the
problem is to open the ui file with a text editor and remove the tag.
So I did and fixed it.
=> Closes #209 -- UI complains about missing widget

.gitignore, Vagrantfile, dev-doc/vagrant.markdown, provision.yml, vagrant/files/brewtarget.conf, vagrant/login, vagrant/provision.yml
I added Vagrant infrastructure to make it easier to try out the new Postgres support.  This PR includes an Ansible playbook which configures the machine with the correct version of Postgres & configures the database.
Documentation is included in dev-doc/vagrant.markdown
=> Use vagrant for development

configure
The Debian/Ubuntu checks were causing the configure script to die on OS
X.  This is a really cheap fix.
=> Fix configure script for OS X

src/MainWindow.cpp
Right now, if you modify the hop usage percentages or the IBU formula, you
have to restart brewtarget. This was surprisingly annoying to me, so I fixed
it.
=> Closes #223 Changing IBU formula or mash/fwh percentages, nothing happens

src/database.cpp, src/database.h
Two problems, and a few cleanups.
The first problem was that newMashStep() wasn't calling insertNewMashStep(),
so the extra two steps to connect the mashstep to its mash weren't being done.
In fixing this, I was able to remove both insertNewDefaultIngredient and
insertNewDefaultMash. Nice little bonus there.
The second problem was I had missed a signal when I removed the SetterCommand
class. Basically, it never signaled anything had changed. I added the signal
back in, and things are happy again. I've tested by mucking around in the
mashstep editor and playing with the hops.
In the process, I found a few methods that hadn't been updated to use the hot
new try-catch process or were doing it wrong. I cleaned those up.
=> Fixes #221 - Can't add mash step in dev

src/brewtarget.cpp, src/brewtarget.h
Someday I'd like to get Brewtarget to build on BSD.  This is one very tiny step towards that goal.
This does change the behavior slightly in that the single-instance restriction is only enforced if the user is using SQLite.  I don't think there is any harm in allowing multiple instances to run against Postgres. (Although I may doubt the usefulness)
=> Make running instance check less Linux specific

src/BtLineEdit.cpp, src/BtLineEdit.h, src/unit.h
This refactor does three things. There is no real change to functionality, I'm
just moving some code around and removing redundancies.
First, FieldType was mostly the same as Unit::UnitType. So I removed
FieldType, extended Unit::UnitType enough to cover the difference and modified
the code to use it. Trivial, but pleasing.
Second, I removed the switch() from the initialization. Each type now simply
sets what it wants for _unit. It's about the same number of lines of code, but
I think it reads slightly better.
Finally, the big one. In other experimental work, I discovered that using
Q_PROPERTY for the editField, forcedUnit and forcedScale along with providing
the READ and WRITE members caused Qt to automatically populate the information
based on what's in the UI files. This means I could …
=> A pleasing rework of BtLineEdit

src/brewtarget.cpp, src/brewtarget.h
Refactor of Brewtarget::ensureDirectoriesExist and related methods so
that:
1) Required directories are created at startup
2) Failure to create said directories is no longer fatal to
Brewtarget::initialize
=> Fixes #210: Missing dirs fatal to initialization

src/BtLineEdit.cpp, src/BtLineEdit.h, ui/ogAdjuster.ui, ui/optionsDialog.ui, ui/primingDialog.ui, ui/refractoDialog.ui, ui/styleEditor.ui, ui/yeastEditor.ui
Testing on _section.isValid() didn't work after I defined the Q_PROPERTY. It
set the property to an empty string, which was valid if empty. Since we almost
never defined configSection on a BtLineEdit, this meant we didn't invoke the
complex math to find the proper configSection.
This commit fixes that. In the process if chasing this problem down, I found a
few dialogs that were not properly defining the configSection, so I fixed that
too.
=> Closes #230 -- buggy refactor

src/equipment.h, src/mash.h, src/style.h
In all the work I did on the database, I somehow forgot to add the two
required properties to these three items. This patch fixes that oversight.
=> Closes issue #237 -- Deleting equipment dumps core

src/MashWizard.cpp, src/database.cpp, ui/mashWizard.ui
According to both sqlite and postgres, the order in which rows are returned is undefined unless an order by clause is used. In postgresql, it seems "undefined" means random. In sqlite, it seems "undefined" means in row-id order.
When we got the mash steps, we didn't specify the order. It happened to work for sqlite, but not for postgresql. This patch adds an order by clause to make sure the order isn't "undefined".
I've also really horked the mash wizard interface around. Having brewed with it, I like it.
=> Closes #244 -- New mash type are behaving poorly (for reals)

src/RecipeFormatter.cpp, src/RecipeFormatter.h
I removed the cssName variable and simply sent the desired css resource in the
call to getCss(). I also found a small error in the misc table where we
weren't open the table row, which caused weird output.
=> Closes #251 - Bad css on recipe output

CMakeLists.txt, src/EquipmentEditor.cpp
Simple fix -- make certain the edit field refers to the actual field being edited. This is kind of a hot bug.
Any chance I can talk anybody into reverting to the UI files until I can get the QML files working?
=> Closes #214 -- error in equipment editor definitions

src/BtLineEdit.cpp
Somewhat simple fix. Basically, when I did the scales for input, I changed the
symantics of what the "force" flag means in BtLineEdit. I just didn't change
everything.
There's a signal that needs to be emitted when the field changes, but I only
want it emitted when the user enters a new value in the field. The previous
logic used the forced flag, which was clever but wrong. When I changed the
symantics, I should have changed the flag. This commit fixes that.
And a new rule. Don't use one flag to do two different things. Use different
flags.
=> Closes #255 - Adjusting volume on preboil tab

src/database.cpp
This resolves the crash, but the table view is not updating yet. I'll open another bug for the update.
=> Fix for #265 - Moving mash steps causes crash

src/recipe.cpp
Since the recipes are not loading the calculated values from the database, we can use the _uninitializedCalcs bool to determine if we need to call set or emit. If the recipe is just being loaded, _uninitializedCalcs will be true. After the initial load, it will be set to false. If it is false, call set and or emit  for changes. This stops the database getting dirty when no changes are made, and is a minor code change. And if something is changed, the database will then get dirtied, I'm still working on getting the values from the database during loading, but haven't found the right location yet. Since the same functions are used to set the database values in the first place, they should match anyways.
Fixing should be faster now the I got the project loading and running in QtCreator. A …
=> Fixes #270: avoid recipe recalc on load

src/MashStepTableModel.cpp, src/MashStepTableModel.h, src/MashStepTableWidget.cpp, src/database.cpp
That was .. a mess. I don't know how far back this error goes, but I think its
old.
First, the SQL statement in Database::swapMashStepOrder was wrong. As
@greggree noticed, it was using msid instead of mash_id. The update itself
changed the stepNumber to be the id of the steps, which ... well, just wasn't
right. So I fixed that, and reworked the QString a little.
Second, there was nothing in the MashStepTableModel to do the right thing when
the stepNumber changed signal was received. I added a method that just removes
the rows and re-adds them. I do not disconnect any signals, which may come to
haunt us later.
I think this fixes the issues.
=> Closes #267 - Moving mash steps doesn't update form.

src/EquipmentEditor.cpp
Currently if you make a mistake in the equipment editor you are warned
about the error, but are not given a chance to correct the problem
before the change is saved.
This commit removes the current default QMessageBox::OK button from the
warning box, and replaces it with QMessageBox::Save/Cancel buttons.
This change gives a user a chance to make corrections with a minimal
number of interactions without changing context.
I'm hoping this is a trivial change, but if it interferes with a larger vision for
interactions: let me know :bread:
=> Add Save/Cancel button to equipment warnings

src/brewtarget.cpp
Late initialization for the win. Basically, QDir::canonicalPath() will return
an empty string if the directory doesn't exist. When starting with no existing
~/.config/brewtarget, this caused an empty user_data_dir string to be written
to the config and every start after that tried to find its db in cwd.
I simply delayed creating the config entry until after we ensured all the
directories existed.
=> Closes #272 -- Default database directory location

css/brewday.css, css/recipe.css, src/RecipeFormatter.cpp
Really, this fixes a lot more than #88. It fixes a lot of html/css compatibility issues that were screwing up the rendering of the html in QTextBrowser and the printout. Something is still adding a large border to the printout version, but I will leave that for another bug fix.
- http://doc.qt.io/qt-5/richtext-html-subset.html
- https://validator.w3.org/check
- https://www.sitepoint.com/understanding-and-using-rem-units-in-css/
- https://www.w3.org/TR/1999/REC-html401-19991224/
- http://www.freeformatter.com/html-formatter.html
=> Fixes #88: high dpi printing

src/brewtarget.cpp
Success is no longer tracked. The #ifdef prevented this error from being
surfaced until I actually tried building on windows.
=> Closes #292 -- Windows build fails

src/MashDesigner.cpp
The slider didn't really reverse. Its behavior simply didn't make sense.
The max temp label is taken either as the configured boiling point of water (bpow, for short) or 100C. In other words, it is treated mostly like a constant and not calculated.
The min temp label, on the other hand, is calculated. We never bothered to check if the results made any sense. While I kind of see the point of staying true to the maths, I think we should consider physics too.
I have put a number of checks in place to make sure if the temperature exceeds the configured bpow, the temperature is set to the bpow. The min/max labels will not exceed the bpow, the temperature label will not, the step starting or target temps will not either.
=> Closes #283 -- temperature slider reversal

src/RecipeFormatter.cpp
QTextDocument::toHtml() makes a full HTML doc, including all the necessary head, body, etc. tags.
Qt5 introduced QString::toHtmlEscaped(), which simply escapes the contents of the string for HTMLness, which is much more like what we need.
=> Closes #277 - Nested html documents in recipe printout

src/MainWindow.cpp, src/database.cpp
Deleting had nothing to do with it, but adding a new hop did. For reasons I still do NOT understand, the hop table was attempting to refresh itself on delete. I went through any number of interations, but could never quite figure out why.
This is the easiest of the fixes I found -- the database isn't closed until after we tear all the windows down. Since MainWindow doesn't open the DB, it shouldn't close it either. I still cannot explain why the hop editor alone does this, and not the misc editor.
=> Closes #116 - Crash at closing after deleting hop

src/BtDatePopup.cpp
This PR automatically defaults the "First Brewed Date" for new recipes to the current date and fixes #301 
Potential Gotchas: 
* Since it's in the code for `BtDatePopup`, does that mean this modification will only be called when the app is opened? Or maybe compiled? Sorry, still getting familiar with the codebase.
=> set date for first brewed to today's date

src/database.cpp, src/database.h
I had previously been skipping the settings table when copying a database. That didn't work, but I couldn't use an insert line. This solution is to special case the settings table and use an SQL UPDATE instead of an INSERT.
It required a new method, renaming an existing method and changing some variable names to better indicate what they are doing.
=> Closes #306 - Copy databsae doesn't copy the settings table properly

src/BeerXMLElement.cpp, src/BeerXMLElement.h, src/BtTreeItem.cpp, src/BtTreeModel.cpp, src/database.cpp, src/database.h, src/equipment.cpp, src/equipment.h, src/fermentable.cpp, src/fermentable.h, src/hop.cpp, src/hop.h, src/instruction.cpp, src/instruction.h, src/mash.cpp, src/mash.h, src/mashstep.cpp, src/mashstep.h, src/misc.cpp, src/misc.h, src/recipe.cpp, src/recipe.h, src/style.cpp, src/style.h, src/water.cpp, src/water.h, src/yeast.cpp, src/yeast.h
If you read the issue, most of this commit should look familiar. The big changes are explained in there.
Previously, we requested the entire row for an item, and then returned one column. Now, we request the one column we want, for a 50% speed improvement. This required us to change how we prepare and cache our queries. selectAll is gone, as is the method that created it. selectSome is used now, and built on the fly.
We now cache four attributes: name, folder, deleted and display. Each of those attributes is now defined in BeerXMLElement. This required removing all of the code from equipment, fermentable, hop, instruction, mash, mashstep, misc, recipe, style, water and yeast that dealt with setting and getting names.
These two changes resulted in the load times for brewtarget to drop from …
=> Closes #309 - Database performance

src/database.cpp
Just had to make sure we cleared selectSome before we closed the connection to the database.
=> Closes #311 - Core dump when closing brewtarget

src/database.cpp
@mordante was correct, both in diagnosis and the suggested fix. Thanks for the bug report and the patch.
I believe this was a left over for an attempted refactoring of the updateEntry() method signature. In other words, mea culpa
=> Closes #315  Updating the inventory seems broken

src/database.cpp
While initialising the database for a new user a random issue occurred.
Every now and then the initialisation failed with a SQL error.
The issue seemed to happen with a record named something like
»Harry's rolled…«. I have not investigated why it is random, nor was I
able to find a similar record in the database.
In order to reproduce the issue I modified the default_db.sqlite database.
I changed the fermentable entry for »Acid Malt« to »Acid Malt'X«. This led
to a reproducible error:
[20:22:44.468] ERROR : void Database::populateChildTablesByName(Brewtarget::DBTable) SELECT id FROM fermentable WHERE ( name='Acid Malt'X' AND display=1 ) ORDER BY id ASC LIMIT 1 unrecognized token: "X' AND display=1 ) ORDER BY id ASC LIMIT 1" Unable to execute statement
[20:22:44.468] ERROR : void …
=> Properly escape SQL statements.

src/BrewDayScrollWidget.cpp
When the brewday is printed without a style or equipment the application
crashes. The same happens when the print preview is requested.
Fixes issue #250.
=> Fix a crash when printing the brewday.

src/main.cpp
While working on issue #319 the application terminated with the following
error message on the console:
terminate called after throwing an instance of 'QString'
Instead of logging this message on the console show a message box to the
user with the contests of the QString thrown. Do the same for
std::exceptions, and a generic message if the exception is of another
type.
=> Improve handling of fatal exceptions.

CHANGES.markdown, src/database.h
When an ingredient is copied by copying a recipe the newly created
ingredient's parent was the original ingredient. This led to two issues:
* The ingredient could no longer be deleted from the original recipe.
* The inventory of the new ingredient was empty. (Issue #72)
Setting the parent of the newly created ingredient to the parent of the
original ingredient fixes both issue.
Note: since I'm not too familiar with the database structure, please
review carefully; I might have missed something.
=> Link ingredients to the original parent.

src/BtLabel.cpp, src/BtLabel.h, src/BtLineEdit.cpp, src/BtLineEdit.h, src/CMakeLists.txt, src/DiastaticPowerUnitSystem.cpp, src/DiastaticPowerUnitSystem.h, src/OptionDialog.cpp, src/UnitSystems.cpp, src/UnitSystems.h, src/brewtarget.cpp, src/brewtarget.h, src/unit.cpp, src/unit.h, ui/fermentableEditor.ui, ui/optionsDialog.ui
It adds the diastatic power units Lintner and Windisch–Kolbach. They are
selectable for the user in:
- The options dialogue.
- The fermentable editor dialogue.
Note since your collaborating guide likes to merge all changes in a squashed commit, I didn't split this patch in smaller chunks.
=> Implement the diastatic power unit.

src/FermentableEditor.cpp
This fixes the problem with the decimals in case #314. The val number of
decimals is now set to 0 when the value is set.
=> Resolves #314 "Number of decimals for the color ..."

src/MainWindow.cpp, src/MainWindow.h, ui/mainWindow.ui
I've reduced the almost 400 line MainWindow constructor to 66 lines (including comments), mostly by moving the obvious groupings into other private methods. I find this a lot easier to search and read.
I've also moved a few of the signals to the newer method pointer syntax, because I think the syntax is cleaner and easier to read. It also provides compile time checking instead of runtime. And that is always better. This required removing the setRecipe(QModelIndex) method, but that's no great loss. It was only used in two places, and both of those can handle null pointers on
their own.
=> Refactoring MainWindow's constructor

src/brewtarget.cpp
Suppressing a «WARNING : Bad diastatic_power_unit type: Linter» at the startup.
Just a typo fix in a source file.
=> Lintner typo fix

src/MiscEditor.cpp
The misc editor was not storing inventory amount for an entry. Also, I checked other editors to make sure nothing was missing, seems like that was the only one.
=> Fixed misc editor to save inventory amount

src/BtLineEdit.cpp
This is a hard thing.
The essence is that in BtLineEdit::setText(BeerXMLElement *element), the conversion went from QVariant to QString to double. The problem was that the QString ended up as something like "1.045". The conversion from QString to double is locale aware, so en_US would get 1.045 but locales like bt_PR would get 1e3+45.
I fixed this by replacing the QVariant->QString->double conversion with a QVariant->double conversion. It *seems* to work -- I've tried this with en_US, bt_PR, de_DE and fr_FR and they all *appear* to do the right thing.
I don't think we need to fix anything else. The values written to the database are written as doubles, so this kind of conversion is irrelevant. On the other hand, I have demonstrated an annoying inability to test my own code and my database …
=> Possibly closes #166 and #158

src/MashDesigner.cpp, src/MashDesigner.h
When using the Mash Designer, the upper limit of the range for the "Infusion Amount" and "Infusion Temp" sliders is now restricted by the collected wort vs. target boil size as well as the mash tun fullness.
=> Limit max infusion amount in Mash Designer by target boil size

src/database.h
Reworked `template<class T> void remove(QList<T*> list)` to leverage `template <class T>void remove(T* ing, bool emitSignal = true)` rather than doing all the deletion (and emiting signals) itself.
Fixed #342
=> Fix issue #342

src/MashDesigner.cpp, src/MashDesigner.h, src/MashWizard.cpp, src/recipe.cpp, src/recipe.h
Moved the recently added `targetTotalMashVol_l` and `targetCollectedWortVol_l` to the recipe so they could be reused in the Mash Wizard.
=> [WIP] Fix calculations for no-sparge

README.markdown
As per comments in Issue #337 I have made the following changes:
- added libqt5sql-psql as a dependency
- changed libqt5svg5 to libqt5svg5-dev
I tested the build and it worked fine [as far as I can see].
=> Update README - correct dependencies

ui/brewNoteWidget.ui
Bug #54 started with an inconsistency on some tooltip labels between the brewnote ui and the help manual. This PR (along with one in the [manual repo](https://github.com/Brewtarget/manual/pull/18)) resolves that inconsistency. I suggest that additional fields and UI changes (as mooted in #54) can be added in future releases with the appropriate DB schema.
I need someone to confirm I've used sane tooltips for Strike Temp and Final Temp.
=> Closes bug #54

src/BtTextEdit.cpp, src/BtTextEdit.h
Not being able to save the notes finally broke me. The textChanged signal was being overridden so it was never triggered, changing the function name works for me. Should fix #365
=> fixing BtTextEdit so that it saves text on exit

CMakeLists.txt
The CMake code seems to really not like having the CMAKE_INSTALL_PREFIX
as anything else than "/usr/" on Debian but as far as I can see, there
is no reason for it.
Obviously, that must have been done for a reason in 2010, but it's not
obvious to me. Furthermore, the Filesystem Hierarchy Standard
specifically mentions that sys admin should install software in
/usr/local and not /usr, the last being only for read-only files.
Furthermore, I think a newer practice is to install apps in /opt/
instead.
The goal of this push request is mainly to stop CMake shooting at me
every time because I want to install in the standard location.
=> Removed the Debian /usr/local warning.

src/recipe.cpp
Fixes #358 
Code was in place in Recipe::recalcOgFg() to determine the number of points from nonfermentable sugars (i.e. lactose), but the ultimate FG calculation ignored these and simply applied the yeast attenuation to all of the fermentable sugars. Doing so resulted in reduced FG values in recipes using Milk Sugar (Lactose), as identified in bug #358.
This PR fixes corrects the calculation so that the gravity points from unfermentable sugars are directly included in the FG without attenuation.
Someone needs to review the revised algorithm (key changes are in lines 2045-2051 of the updated recipe.cpp).
Additional changes include refactoring the 'nonFementableSugars_kg' variable in various places within recipe.cpp to correct the misspelling, and adding comments to explain each step of …
=> Fix #358 Lactose is calculated as fermentable in FG calculation

src/database.cpp
This fixes #341 
It looks like the display wasn't being updated when an ingredient is removed.  Calling recalcAll seems to be the simplest solution.  One could figure out what type of ingredient was being removed and call that ingredient's recalc method, but I think recalcAll is simple and less prone to bugs.
=> Added a call to recipe->recalcAll in removeIngredientFromRecipe in Database

src/MainWindow.cpp, src/database.h
This can be triggered by:
*  Creating a new Vagrant machine
* Build & run Brewtarget in VM
* Start brewtarget 
* Press style or equipment editor
or
* Press right mouse on top element in recipe, style, equipment, etc. and press remove.
I think it is related to no recipe being loaded.
=> Fix various crashes when no recipe is loaded

src/MainWindow.cpp
Double clicking in the name column of an item in the Fermentables, Hops,
Misc, Yeast or Mash tables pops up the edit dialog for the currently
selected item.
This closes issue #350.
=> Double clicking opens edit dialogs

ui/brewNoteWidget.ui
This will hopefully clarify how the brew notes view works, and should help a bit with #398.
=> brewnote: Make some label texts clearer

src/BrewNoteWidget.cpp, src/DatabaseSchemaHelper.cpp, src/DatabaseSchemaHelper.h, src/brewnote.cpp, src/brewnote.h, src/database.cpp, ui/brewNoteWidget.ui
This adds projected and actual attenuation to the brewnotes view. Also
adds actual attenuation field to brewnote database, which requires the
database to be updated with the "attenuation" field.
=> brewnotes: Add attenuation fields

src/DatabaseSchemaHelper.cpp, src/DatabaseSchemaHelper.h
This includes migration code for adding the "attenuation" field to the
brewnotes table.
This should fix the migration issue introduced by #401.
I verified the migration by checking that the "attenuation" field in the table "brewnote" is *not* present in version 6 of the database:
`
$ echo ".schema brewnote" | sqlite3 ~/.config/brewtarget_v6/database.sqlite | grep attenuation
`
.. and that when I copy the v6 database into ~/.config/brewtarget, restart brewtarget, and open up the brewnotes, the attenuation field *is* present in the database:
`
$ echo ".schema brewnote" | sqlite3 ~/.config/brewtarget/database.sqlite | grep attenuation
recipe_id integer, attenuation REAL DEFAULT 0.0,
`
=> Database: Bump schema to version 7

Vagrantfile, vagrant/provision.yml
The old wily box had too old versions of Qt and cmake, so update to Xenial.
The Xenial box does not have python installed, so it can not run Ansible scripts - so install python first in the playbook.
Lastly, increase ram of the virtualbox to 2GB, otherwise compilation fails with out-of-memory errors.
=> Update Vagrant box to Ubuntu Xenial64

src/MashDesigner.cpp, src/MashDesigner.h
I got too aggressive in making changes/improvements in my last PR - this is a much more scaled back attempt to resolve #94 in the develop branch.
This PR updates MashDesigner to check if the current step being worked on is heating or cooling the mash. Key changes were then made to `minTemp_c()`, `maxTemp_c()`, and `minAmt_l()` so that these methods behave appropriately when the mash is cooling rather than heating. Sanity checks were updated in a number of other methods - previous assumptions that the mash must be getting hotter were broken.
In addition, I made one small change to update slider positions/values when a new target temperature is entered. This ensures that values held over from the previous step don't carry over if a user does not move either slider on the new step.
All …
=> Resolves #94 in develop branch

src/EquipmentEditor.cpp
Fixes #404 for label in equipment editor. Image 7 on page 10 of the PDF needs to be updated accordingly. No text needs to be changed in the manual. 
@rocketman768 Is there a copy of the manual other than the pdf that can be updated, or do you and @mikfire handle the manual directly before each new version release?
=> Specific heat unit label fix #404

src/MashDesigner.cpp
This fixes the following warning, currently present when starting
brewtarget:
QObject::connect: No such slot MashDesigner::typeChanged(int) in
/home/jonte/bt/src/MashDesigner.cpp:65
QObject::connect:  (sender name:   'comboBox_type')
QObject::connect:  (receiver name: 'mashDesigner')
=> MashDesigner: Fix comboBox_type::activated

src/brewtarget.cpp
If brewtarget directory is configured but non-existent, we should fall back to default location.
Use case for this is when brewtarget directory is shared amongst many users.
Since config file takes absolute path, we can't just set ~/.config/brewtarget to accommodate.
With this patch if directory is misconfigured or doesn't exist, we would use the same guessing mechanism.
Please let me know if there is anything I still need to do and thank you for this awesome piece of software.
=> Use default directory in case of misconfiguration.

ui/fermentableEditor.ui, ui/hopEditor.ui, ui/yeastEditor.ui
There are several fields in these editors that do not grow when the window
is resized larger or are not big enough to fit content. Increase the max
size of these fields so that they can accommodate the content.
=> Improve fermentable, hop and yeast editor layout

src/fermentable.cpp, src/fermentable.h
Unlike the yeast and hop inventory handling, fermentables were storing
the inventory amount directly within the class. This wasn't being
updated properly when brewing a recipe. Switch to the BeerXMLElement
(base class) setInventory() and getInventory() methods to bring it
inline with the hops and yeast.
Fixes #396.
=> Reduce fermentable inventory when brewing a recipe.

src/BtTreeItem.cpp
Utilizing the same functions as the fermtable in the recipe (this also adds the unit after the color).
=> Closes #345

scripts/add-to-default-db.py, scripts/sqlitediff.sh
* sqlitediff.sh: allow comparing against current uncommitted changes. Useful for people adding items to the default database for checking what has been added before committing.
* add-to-default-db.py: fix `addIng()` to work with Python 3 (`zip()` doesn't return a list).
* add-to-default-db.py: don't require JSON to include all types of ingredients.
=> Some utility script changes.

CMakeLists.txt
Debian based LTS distros no longer supply libqt4-webkit. It has been replaced with libqtwebkit4. Resolved in CMakeLists.txt
=> Resolved dependency issue on Debian based LTS systems

src/database.cpp, ui/mashStepEditor.ui
Those new type of mash steps were available in the main window, but not on the edit window. This fixes it.
=> Add missing combo box items in mash step editor

src/TableSchema.cpp
Mashsteps don't have folders. Removed the declaration from
TableSchema::defineMashSteps()
=> Closes #461  -- SQL Database Error in mashstep

src/database.cpp
Brewtarget Develop crash when importing recepies containing Mashes with mashsteps.
Crash happens due to the fact that the Mashsteps was inserted before the mash was created resulting in a Foreign key contraint error.
I also made the log messages a bit more detailed to see where the log was generated.
=> Fixing import crash

cmake/modules/NSIS.template.in, src/brewtarget.cpp, src/brewtarget.h, src/database.cpp
Database directory pointing to the wrong location on Windows clients.
On new installation in windows, where there was no old db to convert, brewtarget was trying to create the new DB in the Programs directory. That directory, which for most normal users, is a write-restricted directory.
I changed the default location to the Appdata\roaming directory on windows builds instead while keeping the original data direktory intact in Linux and MacOS.
This issue is only showing up when you install brewtarget to the Default location C:\Program Files (86)\ or C:\Program Files\
this PR fixes issue #486 
Closes #486
=> Fixes: #486 - DataDirectory now pointing to Appdata\roaming on windows clients.

CMakeLists.txt, cmake/modules/NSIS.template.in, src/MashWizard.cpp, src/brewtarget.cpp, src/brewtarget.h
This PR fixes the Following issues with Stable/2.4.0
* Building on Windows, removed old QT-dependencies from CmakeLists.txt
* Modify the NSIS-Installer template to include Visual Studio Runtime for making brewtarget run on Winodws 7 (automatically installs if not present at target system)
* Fixing missing Include in MashWizard.cpp
* Fixing NSIS installer to copy old DB to the users Roaming folder
* modify brewtarget.cpp to use Users Roaming folder as default db location
* adds the vcredist to repository so others can build the windows installer.
Some of these changes is not present in Develop, maybe fix a PR for those?
Not available in Develop-branch:
* VS Runtime installer
* NSIS settings for installing VS Runtime
_All above is tested on Windows 10 an Windows 7, including upgrading from …
=> 2.4.0 - fixup for windows build and default DB location

src/MainWindow.cpp, src/database.cpp, src/database.h
(This is my first pull request for brewtarget, so grateful for any feedback about process, standards, etc.)
Bug #1109751 is basically a small feature request for the user to be able to choose the file name into which a manual DB backup is created.
I modified database class to:
- Be able to report the default name it uses for the backup file - new method getDefaultBackupFileName()
- Be able to do a backup to a fully qualified file name - new method backupToFile()
- Have existing method backupToDir() work by calling backupToFile() - to avoid duplicate code
- Add some debug-level logging
I modified MainWindow::backup() to:
- Ask the user to select a file instead of a directory, but have the default filename already in the dialog - so the user doesn't have to specify anything more than now if …
=> Fix for Issue #497 – (Bugs 1109751 and 1372087 from launchpad)

src/brewtarget.cpp
2-line fix to log whether we are using XDG_CONFIG_HOME or HOME to find config dir, and what value it is
=> Additional logging for Issue #470

src/beerxml.cpp, src/database.h
This is a fix for a key issue in https://github.com/Brewtarget/brewtarget/issues/500 - though there may be other bugs to fix too.
BeerXML is making copies of the singleton Database object, which leads to strange bugs - eg it adds a style but the rest of the program can't see it because the in-memory reference to it in allStyles is only in the _copy_ of Database made by BeerXML.  BeerXML is able to make copies of Database, even though Database's copy constructor and copy assignment operator are private, because BeerXML is a friend of Database. 
The fix is to use the more modern approach to preventing copying - viz explicitly delete the copy constructor and copy assignment operator.  Compilation errors then tell you all the places in BeerXML where it is trying to copy the Database singleton …
=> Fix for issue 500 - Copy being made of Database singleton

configure
Prevent configure script from exiting early on non Debian/Ubuntu systems.
While at it clean up the mkdir invocation and redundant semicolons in the script.
=> Fix configure script

src/Log.cpp, src/Log.h
As jimdbr so correctly found is that the getTypeName was incorrectly defined in Log.cpp.
This PR fixes that issue.
Built and testes on both windows and Linux.
=> Declaration of getTypeName was incorrectly declared in Log.cpp. fixed.

src/MainWindow.cpp
My usual process in creating a new recipe is to create the recipe; set the style and equipment; add fermentables, hops and yeast; and then define the mash.
The undo code missed this possible path and assumed there would always be a mash. In my path, mash was null and we sigsegv'd.
The fix was to move the creation of the undo objects for the tunWeight and tunSpecificGravity properties to earlier in the code, where we had already checked to make sure we had a mash. We also modified those two properties regardless of how the user responds to the dialog we prompt, so moving the undo made that work a bit better.
=> Closes #507 - adding equipment to new recipe

src/BtTreeItem.cpp, src/Log.cpp, src/Log.h, src/OptionDialog.cpp, src/brewtarget.cpp
Now it starts to log to file after options has been read.
Early logging is sent to stderr, and Logging is enabled by default.
Error was thrown when Linux did not supply a valid path for log file at initialization, this was changed to only log to stderr at startup.
On windows there was a path supplied on my machine at least, but not on my linux laptop.
=> Fixing Log initialization.

src/InventoryFormatter.cpp
This is a fix for https://github.com/Brewtarget/brewtarget/issues/466.  Pretty self-explanatory I hope.
=> Enhancement to add alpha acid % in inventory report

src/MainWindow.cpp, ui/mainWindow.ui
This is a fix for https://github.com/Brewtarget/brewtarget/issues/403 to make the "brew notes" functionality more visible (ie not just accessible from a right-click on the tree of recipes).
=> Add a Brew It button to recipe

src/RadarChart.cpp
Fix for https://github.com/Brewtarget/brewtarget/issues/538
I don't have a Windows build set up on my machine, so it would be great if someone who has could quickly check this compiles as expected.
=> Extra define needed for pi constant for RadarChart on Windows

.github/workflows/linux-ubuntu.yml
PR #515 introduced a new dependency, but the ci/cd system wasn't aware
of it. I am hoping this will resolve those issues.
=> Need xerces included

src/BtTreeView.cpp
Some fast fix for deleting folder.
Another solution was to add method name() to class BtFolder.
=> fix #338 Delete folder segfault

ui/mainWindow.ui, ui/waterEditor.ui
I swapped the Ca and Cl columns on the water editor. I had intended for all the cations to be in one column and the anions in the other. The previous commit got these two backwards.
I also moved the "Brew it!" button into the grid. This way, it stays a constant size regardless of how big the Style drop down becomes.
=> Two small UI adjustments

src/TableSchema.cpp, src/TableSchema.h, src/database.cpp, src/database.h
This was several problems all sort of rolled into one.
The initial problem was likely me being clever. Instead of updating existing things and inserting new things, we updated existing things and created new things and then updated them. This had a cascade failure
that ended up showing blank entries in the trees. They were properly loaded on restarting brewtarget, but the idea was wrong.
The fix was to update that which existed, and create that which didn't. This required a lot of reworking in TableSchema. The m_properties are keyed by the name of the property, except for things like typeString.
This caused problems, and I finally wrote TableSchema::allProperties to resolve.
By the time I was there, I realized the updateDatabase was a mess too. After much thought, I removed the update …
=> Closes #564 -- updating the database is misbehaving

src/CMakeLists.txt
When Compiling on Windows the icon was compiled in the source tree making git believe there is a new file to add to the source!
This has nagged me for awhile, finally got around to fixing it.
=> Fixing annoying windows icon build location

src/TableSchema.cpp
There are two generateInsert* methods. generateInsertRow() is intended for database to database copies, as it includes things like foreign keys. generateInsertProperties is intended for writing entire objects to the
database.
generateInsertRow() needs to be keyed by the column name. We do not have the object at that point and the object doesn't know the foreign key names.
=> Closes #580

src/beerxml.cpp, src/database.cpp, src/xml/XmlNamedEntityRecord.h
The first issue is anything using allPropertyNames is probably doing it wrong. Whenever we are storing a type string in the database, there is a difference in the property names of the objects (which is how we key the m_properties hash) and the name of the property we store in the
database. This causes many problems and we should fix it some day. Until then, we should always use allProperties() to loop, and request the propertyName().
The second issue was a missing property in the XMLRecord::FieldDefinitions for BEER_XML_MASH_STEP_RECORD_FIELDS. Since we didn't map the infusion temps to a property, they never got read.
The final issue was that we were treating mashes has having to be unique. They do not, and enforcing it caused problems when importing two recipes, each with an unnamed …
=> My half to close #576 - beer xml imports don't seem to be working

src/beerxml.cpp, src/database.cpp, src/database.h, src/recipe.cpp
This is primarily improving the logic for how we decide whether to make a copy of whatever we're trying to add to a Recipe (Hop, Fermentable, etc).  Both the XML import and the undo/redo functionality benefit from having the Recipe object itself work out what the right thing to do is in such circumstances.
=> More XML import fixes

src/database.cpp
Close #589 
Null checking added to addToRecipe (mash) as new recipes do not have mashes by default the copy mechanism crashed when trying to handle a nullptr.
Quickfix waiting for a possible rework further down the road.
=> Quickfix with null-check on mash when copy recipe

src/EquipmentEditor.cpp, src/database.cpp, src/database.h, src/model/Equipment.cpp, src/model/Fermentable.cpp, src/model/Hop.cpp, src/model/Instruction.cpp, src/model/Mash.cpp, src/model/MashStep.cpp, src/model/Misc.cpp, src/model/NamedEntity.cpp, src/model/NamedEntity.h, src/model/Yeast.cpp
The problem as seen in #596 was directly related to how I reordered the cache and flush.
Changing an existing hop (or anything else) on a non-versioning recipe would cause the NamedEntity:changed() signal to fire before the cache value was updated. Since everybody uses the cache value, nothing would change until we had reason to reload the recipe and re-read the values.
I am somewhat trapped for a solution on this. The order is very specific and versioning requires brewtarget clone before it updates the cache. It simply doesn't work any other way.
This means brewtarget must wait until after the clone decision is made to emit a NamedEntity::changed signal. The cache has to be updated before we signal and that can only be done in the derived class (eg Hop) and it cannot be done in …
=> Partial solution to #596

src/CMakeLists.txt
In Cmake Lists there was an include to Brewken.h instead of brewtarget.h
It's not a showstopper, but to keep things in order. :)
=> Small typo in CmakeLists.txt

src/EquipmentEditor.cpp, src/UiAmountWithUnits.cpp, src/UiAmountWithUnits.h
Fix for https://github.com/Brewtarget/brewtarget/issues/634 plus more general tweak so we get an error message rather than an assert when trying to call `toSI()` for a BtLineEdit that does not related to a physical quantity.  (Though we should fix the inheritance hierarchy for BtGenericEdit etc so that these things get flushed out at compile time.)
=> Fix crash when creating new Equipment

CMakeLists.txt, src/MainWindow.cpp, src/PersistentSettings.cpp, src/RadarChart.cpp, src/WaterDialog.cpp, src/WaterEditor.cpp, src/WaterEditor.h, src/database/ObjectStore.cpp, src/database/ObjectStore.h, src/database/ObjectStoreTyped.h, src/database/ObjectStoreWrapper.h, src/main.cpp, src/model/NamedEntity.cpp, src/model/NamedEntity.h, src/model/Water.cpp, src/model/Water.h, src/tableModels/SaltTableModel.cpp, src/xml/XmlRecord.cpp
So far, this is a fixes for https://github.com/Brewtarget/brewtarget/issues/649 and https://github.com/Brewtarget/brewtarget/issues/662, plus possible fix for missing desktop icon on Windows.
Will push any other fixes into this PR if we find issues over the next few days.
=> Fixes for 3.0.1 release

.github/workflows/linux-ubuntu.yml, .github/workflows/mac.yml, .github/workflows/windows.yml
See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ but, in short, we need to use newer versions of some of our workflow actions as the version of Node.js that they run against is out of support and will be upgraded by GitHub in the near future.
=> Update actions for Node.js upgrade

CMakeLists.txt, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts
Previous PR had a bug that meant it was pulling translation strings only from .cpp files and not also from .ui files.  Have fixed this here.  From a quick test, seems like French translations are working better now!
=> Translations now including .ui files

src/OptionDialog.cpp, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts, ui/optionsDialog.ui
I spotted that the link we offer to people to contribute translations is a bit out of date (https://sourceforge.net/sendmessage.php?touser=938941).  Now replaced with link to relevant wiki page here (https://github.com/Brewtarget/brewtarget/wiki/Translations).
Also, a reference to Brewken snuck in when I was doing a merge, so I've fixed that back to Brewtarget.
=> Update contact link for translators + fix erroneous mention of Brewken

CMakeLists.txt, src/AboutDialog.cpp, src/Application.cpp, src/MainWindow.cpp, src/config.in, src/main.cpp, src/xml/BeerXml.cpp, src/xml/BeerXml.h, ui/mainWindow.ui
Partly tidy-up and partly for https://github.com/Brewtarget/brewtarget/issues/669
=> Slightly improved logging of system/build info

.github/workflows/mac.yml, CMakeLists.txt, src/WaterDialog.cpp, src/database/ObjectStoreWrapper.h, src/tableModels/BtTableModel.h, src/tableModels/FermentableTableModel.cpp, src/tableModels/FermentableTableModel.h, src/tableModels/HopTableModel.cpp, src/tableModels/MashStepTableModel.cpp, src/tableModels/MiscTableModel.cpp, src/tableModels/MiscTableModel.h, src/tableModels/SaltTableModel.cpp, src/tableModels/WaterTableModel.cpp, src/tableModels/WaterTableModel.h, src/tableModels/YeastTableModel.cpp, src/tableModels/YeastTableModel.h, translations/bt_tr.ts
This is another step (I hope) towards fixing https://github.com/Brewtarget/brewtarget/issues/679, plus a stab at a fix for https://github.com/Brewtarget/brewtarget/issues/683
=> More Mac build fixes plus fix for Linux desktop icon etc locations

.gitignore, brewtarget.qrc
Closes #697. 
The place to looks for the images is in brewtarget.qrc. It looks like the file got reworked a while back, and the two title images were dropped.
=> Putting the title back in brewtarget

src/HopEditor.cpp, src/PersistentSettings.cpp, src/model/Hop.cpp, src/model/Hop.h, src/unitTests/Testing.cpp, src/xml/BeerXml.cpp, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts
Specifically https://github.com/Brewtarget/brewtarget/issues/694 and https://github.com/Brewtarget/brewtarget/issues/695
=> Fixes for over-merging from Brewken (extra Hop attributes and incorrect conf file name)

src/BtTreeView.cpp, ui/mainWindow.ui
The logic in BtTreeView::mimeData was broken. As we always set itsa, the std::optional variable would have never been false. This resulted in setting the mime type to `application/x-brewtarget-folder` for anything that wasn't a Recipe, Style or Folder. Since the tables are configured to only accept `application/x-brewtarget-ingredient`, they wouldn't accept the drop.
To fix it, I changed all the tests around. We test for Recipe, Style and Equipment; then we test for Folder; then we test to not be Water. That sets all of the mime types correct. I also added an `application/x-brewtarget-water` in case I ever want to get clever.
=> Fixes #701 drag and drop is broken

src/BtTreeModel.cpp
The dates in the brewnotes were changed from QDateTime to QDate objects. The signature for the signal in BtTreeModel wasn't updated, so the signal was never properly connected.
It is now properly connected.
=> closes #703 - brewnote signal not found

.github/workflows/mac.yml, CHANGES.markdown, CMakeLists.txt, bt, meson.build, src/BtLineEdit.cpp, src/ConverterTool.cpp, src/UiAmountWithUnits.h, src/measurement/Unit.cpp, src/measurement/Unit.h, src/measurement/UnitSystem.cpp, src/unitTests/Testing.cpp, src/utils/EnumStringMapping.cpp
This is for https://github.com/Brewtarget/brewtarget/issues/725
Also a bit more work on the Mac build/packaging trying to fix this library-not-found-even-though-it's-there issue. (Including realised the final step of the Mac packaging was creating an empty .dmg file, which this fixes.)
Also tidied up a few comments.
(I meant this to be two separate PRs, but did things in the wrong order on github.)
NB: I think the changes I've done on looking up unit names slightly change the behaviour when you enter an ambiguous unit name.  Eg, if you type '5 gal', there is sometimes no way for us to know whether you mean US gallons or Imperial gallons - eg because you are using the free-standing conversion tool or you have configured a field's default units to be metric.  At the moment, if there are no …
=> Add case insensitive matching for unit names + Mac packaging fixes

src/database/ObjectStore.cpp, src/unitTests/Testing.cpp
This should, I hope, fix https://github.com/Brewtarget/brewtarget/issues/751 (which is also one of the problems mentioned in https://github.com/Brewtarget/brewtarget/issues/738).
=> Fix for old DBs where fermentable->inventory_id is double instead of int

src/database/ObjectStoreTyped.cpp
Resolving a minor typecast issue, specifically noticed on a postgres setup.  Should address #760
=> Resolve typecast error on fermentation_stages w/ DB interface

CMakeLists.txt, schemas/beerxml/v1/BeerXml.xsd, src/database/ObjectStore.cpp, src/database/ObjectStoreTyped.cpp
Fix `src/database/ObjectStore.cpp` so that it can recover from the case where it finds a "true" or "false" **string** in a table field where it was expecting a boolean (or actually a 0 or 1, since SQLite doesn't have native booleans).
I'm not sure how we end up with a string in a boolean field, but it can happen -- see https://github.com/Brewtarget/brewtarget/issues/766.  Given that we can automatically recover (provided the string holds something sane), we should.
I've tested this locally by manually modifying my DB but, as ever, any corrections or comments are welcome!
=> Error recovery for string-in-boolean field in DB

src/MashDesigner.cpp, src/model/Recipe.cpp
When using keyboard to move slider for mash designer values are not updated.
I've switched the event that we connect to, so this usecase would be supported.
Boil size should also be reduced by the lauter deadspace in calculation.
I've simply substracted it if it's defined in the equipment.
Please take special consideration when reviewing this PR as I'm not a developer by profession.
I'm not aware if this has any impact or implications on other parts of Brewtarget.
Cheers!
=> Improve keyboard usage and reduce boilsize by deadspace.

.github/workflows/mac.yml, bt, src/database/ObjectStore.cpp
This should fix https://github.com/Brewtarget/brewtarget/issues/780 and similar issues.
=> Be more accepting of unexpected DB data types

.github/workflows/windows.yml, CMakeLists.txt, bt, src/RecipeExtrasWidget.cpp, src/database/ObjectStore.cpp, src/widgets/SmartField.cpp, src/widgets/SmartField.h, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts
Fix for https://github.com/Brewtarget/brewtarget/issues/785
The fermentation age fields are handled a bit differently than most other ones.  Although they are a measure of time (duration), we actually treat them as raw numbers because we're only measuring to the nearest day, and don't want to start offering to show things in hours/minutes/seconds etc.  The bug was we were saying "convert this field to its standard units of measurement" when we should have been saying "get this field as a raw number".
EDIT: Fighting a bit to get the Windows build working.  Turns out some of the 32-bit MSYS2 packages/groups we were relying on previously are no longer available.   (Works on my local machine because they are already installed, but not on GitHub Actions because there you install from scratch …
=> Fix for crash when editing fermentation ages

meson.build, src/BtHorizontalTabs.cpp, src/BtHorizontalTabs.h, src/CMakeLists.txt, src/model/BrewNote.cpp, translations/bt_ca.ts, translations/bt_cs.ts, translations/bt_de.ts, translations/bt_el.ts, translations/bt_en.ts, translations/bt_es.ts, translations/bt_et.ts, translations/bt_eu.ts, translations/bt_fr.ts, translations/bt_gl.ts, translations/bt_hu.ts, translations/bt_it.ts, translations/bt_lv.ts, translations/bt_nb.ts, translations/bt_nl.ts, translations/bt_pl.ts, translations/bt_pt.ts, translations/bt_ru.ts, translations/bt_sr.ts, translations/bt_sv.ts, translations/bt_tr.ts, translations/bt_zh.ts
Fix for https://github.com/Brewtarget/brewtarget/issues/789 is correcting the following line of `src/model/BrewNote.cpp`:
`double BrewNote::projVolIntoBK_l() const { return m_projVolIntoFerm_l; }`
to:
`double BrewNote::projVolIntoBK_l() const { return m_projVolIntoBK_l; }`
The other changes are tidying up `BtHorizontalTabs` (specifically pulling code out of the header file into a .cpp file and adding some comments).  This doesn't change functionality but is part of investigating https://github.com/Brewtarget/brewtarget/issues/787.
=> Fix for incorrect BrewNote calculation, plus small tidy-up of BtHorizontalTabs

src/Application.cpp, src/BtHorizontalTabs.cpp, src/BtHorizontalTabs.h, src/MainWindow.cpp
This is a minimal fix for https://github.com/Brewtarget/brewtarget/issues/787.
Also changed current uses of `Q_OS_MAC` to `Q_OS_MACOS` as the former is deprecated according to https://doc.qt.io/qt-5/qtglobal.html#Q_OS_MAC.
=> Fix for text in side tabs not displaying on Mac

CMakeLists.txt
This commit repairs the configuration on Linux machines where we have a recent CMake toolset (VERSION >= 3.29) where FindBoost.cmake module is removed from standard installation.
Setting the policy CMP0167 helps ensure compatibility with older versions of CMake as well.
Note : in this commit we also uniformise Boost retrievala across platforms, not as COMPONENT but as a general dependency.
=> Tweaked FindBoost command in CMakeLists.txt

.github/workflows/windows.yml, .signpath/artifact-configurations/default.xml, CHANGES.markdown, src/serialization/ImportExport.cpp, src/serialization/json/JsonMeasureableUnitsMapping.cpp, src/serialization/json/JsonMeasureableUnitsMapping.h, src/serialization/json/JsonRecord.cpp, src/serialization/json/JsonXPath.cpp, src/serialization/json/JsonXPath.h
Includes fixes for https://github.com/Brewtarget/brewtarget/issues/835
=> Fixes for BeerXML, BeerJSON export.  Plus more on Windows binary signing

CHANGES.markdown, packaging/linux/control.in
First stab at fix for https://github.com/Brewtarget/brewtarget/issues/840.
=> Fix for Qt dependency'

.github/workflows/windows.yml, CHANGES.markdown, schemas/beerxml/v1/BeerXml.xsd, src/model/Recipe.cpp, src/serialization/xml/BeerXml.cpp
This fixes:
- Equipment should be optional in Recipes in BeerXML
- Crash when you mouse-over a Recipe without Equipment
- We should accept "incorrect" BeerXML that has more than one tag on the first line
- We should accept "incorrect" BeerXML that omits one or more of the required `VERSION` tags
See https://github.com/Brewtarget/brewtarget/issues/853.
Also turning off the automatic signing requests on the overnight Windows builds, since there is manual intervention required to approve signing.
=> Some BeerXML fixes

CHANGES.markdown, src/MainWindow.cpp, ui/mainWindow.ui
Fixes https://github.com/Brewtarget/brewtarget/issues/879
=> Fix non-visible drop-downs next to resize bar, plus small tidy-ups

CHANGES.markdown, packaging/linux/control.in, packaging/linux/rpm.spec.in, scripts/buildTool.py, src/Localization.cpp, src/Localization.h, src/OptionDialog.cpp, src/PersistentSettings.cpp, src/PersistentSettings.h
Fixes https://github.com/Brewtarget/brewtarget/issues/889 and attempts to fix https://github.com/Brewtarget/brewtarget/issues/890.
=> Tidy up code that loads translations

CHANGES.markdown, src/MainWindow.cpp, src/model/Boil.cpp, src/model/OwnedSet.h, src/model/Recipe.cpp
Fixes for:
* Opening user recipe causes crash [897](https://github.com/Brewtarget/brewtarget/issues/897)
* Copy recipe crash [899](https://github.com/Brewtarget/brewtarget/issues/899)
=> Fixes for two crashes

src/Algorithms.cpp, src/model/BrewNote.cpp, src/model/Recipe.cpp
This should fix https://github.com/Brewtarget/brewtarget/issues/918
=> Fix places where we are using old ABV formulae

CHANGES.markdown, src/measurement/Unit.cpp, src/measurement/Unit.h
See https://github.com/Brewtarget/brewtarget/issues/924.
=> Fix for not detecting current unit system settings when doing contextless unit conversions
